import type { Metadata } from "next";
import Link from "next/link";
import PageFlowOverview from "@/components/PageFlowOverview";

export const metadata: Metadata = {
  title: "Farmart Site Overview",
  description: "React Flow diagram of every page in the app and how they link together",
};

export default function OverviewPage() {
  return (
    <div className="flex h-screen flex-col bg-white">
      <div className="shrink-0 border-b border-zinc-100 px-4 py-4 sm:px-6 lg:px-8">
        <Link href="/" className="text-xs font-semibold text-brand hover:underline">
          ← Back to Farmart
        </Link>
        <h1 className="mt-2 text-xl font-bold text-foreground">Site Overview</h1>
        <p className="mt-1 text-sm text-zinc-500">
          Every page this app actually has, and the real links between them — generated by
          reading the codebase, not an idealized flowchart. Solid brand-colored edges are
          real `Link`s in the code; dashed edges are gaps (an expected link that doesn&apos;t
          exist yet) or `href=&quot;#&quot;` placeholders pointing at pages from{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 text-xs">PLAN.md</code> that
          haven&apos;t been built.
        </p>
      </div>

      <PageFlowOverview />
    </div>
  );
}
